name: Actions workflow

on:
  schedule:
    - cron: "0/5 * * * *"

  push:

  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
  runs on: ubuntu-latest
  steps:
    - name: List files
      run: |
        pwd
        ls -a