name: Container1
on: push

jobs: 
      node-docker:
        runs-on: ubuntu-latest
        container: 
           image: node
           ports: 8080
        steps:
           - name: Log node version
             run: |
                node -v
                cat /etc/os-release