name: Container1
on: push

jobs: 
      node-docker:
        runs-on: ubuntu-latest
        container: 
           image: node
           ports: 
             - 4001:4000
        steps:
           - name: Log node version
             run: http://localhost:4001/api/items
                #node -v
                #cat /etc/os-release
                