name: MyFirstJob

on: [push]

jobs:
  Docker_images:
    runs-on: ubuntu-latest
    name: Docker Images and Container view
    steps:
      - name: Hello world action step
        working-directory: /usr/bin/bash/
        run: docker build . --file Dockerfile --tag my-image1:$(date +%s)
      - name: Get the output docker image
        run: docker images
      - name: Get the output docker containers
        run: docker ps -a
