name: MyFirstJob

on: [push]

jobs:
  Docker_images:
    runs-on: ubuntu-latest
    name: Docker Images and Container view
    steps:
      - name: Hello world action step
      #  id: hello
        # uses: actions/hello-world-docker-action@v1
        run: docker bulid . --file Dockerfile --tag node-apline-image:$(date +%s)
       # with:
        #  who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output images
   #     run: echo "The time was ${{ steps.hello.outputs.time }}"
        run: docker images
      - name: Get the output docker containers
        run: docker ps -a
